packages:
  - "apps/*"
  - "packages/*"

allowBuilds:
  esbuild: set this to true or false
  msgpackr-extract: set this to true or false

onlyBuiltDependencies:
  - "@prisma/client"
  - "@prisma/engines"
  - "prisma"
  - "sharp"
  - "unrs-resolver"
  - "msgpackr-extract"
  - "esbuild"
